version: 2.1
workflows:
  testing:
    jobs:
      - runner
jobs:
  runner:
    docker:
      - image: cimg/base:2021.11
    resource_class: leightjohnson93/test
    steps:
      - run: echo "Hi I'm on Runners!"
    parallelism: 30
